//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.1
//     from Assets/Tec/Scripts/Inputs/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @InputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""SteeringWheel"",
            ""id"": ""fea69287-cdcd-4f10-b269-d44defa62da8"",
            ""actions"": [
                {
                    ""name"": ""Turn"",
                    ""type"": ""Value"",
                    ""id"": ""b6a8d4cd-fd21-496f-87ee-24de4b8a1592"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PortThrottle"",
                    ""type"": ""Value"",
                    ""id"": ""c9d65ddc-122e-42ba-b19b-50001bccbcc6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StarboardThrottle"",
                    ""type"": ""Value"",
                    ""id"": ""fa2db6de-adaa-4687-9da9-352d9d7ace54"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PortToggle"",
                    ""type"": ""Button"",
                    ""id"": ""14b028bb-29db-401a-a558-fd47e0af1cd7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StarboardToggle"",
                    ""type"": ""Button"",
                    ""id"": ""5e5dfdb3-802c-42e4-9df2-e1b7d604d02e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Day"",
                    ""type"": ""Button"",
                    ""id"": ""0cdd7fa1-fd99-4287-86b6-6f67e973a8e0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Night"",
                    ""type"": ""Button"",
                    ""id"": ""f5017033-bbb0-4f8d-828b-bdfaa2250649"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bcb6196a-04b4-49b2-9832-e653bf1b591e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortThrottle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfaab1da-b363-465a-842e-3bf308780850"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StarboardThrottle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e792a2ee-496b-4f06-8e77-23567bf2e3f9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StarboardToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9cf6541-5e41-4f77-8483-a6bc780a7e70"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcdacf13-8674-4d99-b9a8-4960a689ae7e"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Day"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30d287e0-9e35-48fe-b7ce-8eb967d3a3a5"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ebe5da6-71a8-4a54-906a-28278d07d471"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Night"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SteeringWheel
        m_SteeringWheel = asset.FindActionMap("SteeringWheel", throwIfNotFound: true);
        m_SteeringWheel_Turn = m_SteeringWheel.FindAction("Turn", throwIfNotFound: true);
        m_SteeringWheel_PortThrottle = m_SteeringWheel.FindAction("PortThrottle", throwIfNotFound: true);
        m_SteeringWheel_StarboardThrottle = m_SteeringWheel.FindAction("StarboardThrottle", throwIfNotFound: true);
        m_SteeringWheel_PortToggle = m_SteeringWheel.FindAction("PortToggle", throwIfNotFound: true);
        m_SteeringWheel_StarboardToggle = m_SteeringWheel.FindAction("StarboardToggle", throwIfNotFound: true);
        m_SteeringWheel_Day = m_SteeringWheel.FindAction("Day", throwIfNotFound: true);
        m_SteeringWheel_Night = m_SteeringWheel.FindAction("Night", throwIfNotFound: true);
    }

    ~@InputMap()
    {
        Debug.Assert(!m_SteeringWheel.enabled, "This will cause a leak and performance issues, InputMap.SteeringWheel.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SteeringWheel
    private readonly InputActionMap m_SteeringWheel;
    private List<ISteeringWheelActions> m_SteeringWheelActionsCallbackInterfaces = new List<ISteeringWheelActions>();
    private readonly InputAction m_SteeringWheel_Turn;
    private readonly InputAction m_SteeringWheel_PortThrottle;
    private readonly InputAction m_SteeringWheel_StarboardThrottle;
    private readonly InputAction m_SteeringWheel_PortToggle;
    private readonly InputAction m_SteeringWheel_StarboardToggle;
    private readonly InputAction m_SteeringWheel_Day;
    private readonly InputAction m_SteeringWheel_Night;
    public struct SteeringWheelActions
    {
        private @InputMap m_Wrapper;
        public SteeringWheelActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Turn => m_Wrapper.m_SteeringWheel_Turn;
        public InputAction @PortThrottle => m_Wrapper.m_SteeringWheel_PortThrottle;
        public InputAction @StarboardThrottle => m_Wrapper.m_SteeringWheel_StarboardThrottle;
        public InputAction @PortToggle => m_Wrapper.m_SteeringWheel_PortToggle;
        public InputAction @StarboardToggle => m_Wrapper.m_SteeringWheel_StarboardToggle;
        public InputAction @Day => m_Wrapper.m_SteeringWheel_Day;
        public InputAction @Night => m_Wrapper.m_SteeringWheel_Night;
        public InputActionMap Get() { return m_Wrapper.m_SteeringWheel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SteeringWheelActions set) { return set.Get(); }
        public void AddCallbacks(ISteeringWheelActions instance)
        {
            if (instance == null || m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Add(instance);
            @Turn.started += instance.OnTurn;
            @Turn.performed += instance.OnTurn;
            @Turn.canceled += instance.OnTurn;
            @PortThrottle.started += instance.OnPortThrottle;
            @PortThrottle.performed += instance.OnPortThrottle;
            @PortThrottle.canceled += instance.OnPortThrottle;
            @StarboardThrottle.started += instance.OnStarboardThrottle;
            @StarboardThrottle.performed += instance.OnStarboardThrottle;
            @StarboardThrottle.canceled += instance.OnStarboardThrottle;
            @PortToggle.started += instance.OnPortToggle;
            @PortToggle.performed += instance.OnPortToggle;
            @PortToggle.canceled += instance.OnPortToggle;
            @StarboardToggle.started += instance.OnStarboardToggle;
            @StarboardToggle.performed += instance.OnStarboardToggle;
            @StarboardToggle.canceled += instance.OnStarboardToggle;
            @Day.started += instance.OnDay;
            @Day.performed += instance.OnDay;
            @Day.canceled += instance.OnDay;
            @Night.started += instance.OnNight;
            @Night.performed += instance.OnNight;
            @Night.canceled += instance.OnNight;
        }

        private void UnregisterCallbacks(ISteeringWheelActions instance)
        {
            @Turn.started -= instance.OnTurn;
            @Turn.performed -= instance.OnTurn;
            @Turn.canceled -= instance.OnTurn;
            @PortThrottle.started -= instance.OnPortThrottle;
            @PortThrottle.performed -= instance.OnPortThrottle;
            @PortThrottle.canceled -= instance.OnPortThrottle;
            @StarboardThrottle.started -= instance.OnStarboardThrottle;
            @StarboardThrottle.performed -= instance.OnStarboardThrottle;
            @StarboardThrottle.canceled -= instance.OnStarboardThrottle;
            @PortToggle.started -= instance.OnPortToggle;
            @PortToggle.performed -= instance.OnPortToggle;
            @PortToggle.canceled -= instance.OnPortToggle;
            @StarboardToggle.started -= instance.OnStarboardToggle;
            @StarboardToggle.performed -= instance.OnStarboardToggle;
            @StarboardToggle.canceled -= instance.OnStarboardToggle;
            @Day.started -= instance.OnDay;
            @Day.performed -= instance.OnDay;
            @Day.canceled -= instance.OnDay;
            @Night.started -= instance.OnNight;
            @Night.performed -= instance.OnNight;
            @Night.canceled -= instance.OnNight;
        }

        public void RemoveCallbacks(ISteeringWheelActions instance)
        {
            if (m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISteeringWheelActions instance)
        {
            foreach (var item in m_Wrapper.m_SteeringWheelActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SteeringWheelActions @SteeringWheel => new SteeringWheelActions(this);
    public interface ISteeringWheelActions
    {
        void OnTurn(InputAction.CallbackContext context);
        void OnPortThrottle(InputAction.CallbackContext context);
        void OnStarboardThrottle(InputAction.CallbackContext context);
        void OnPortToggle(InputAction.CallbackContext context);
        void OnStarboardToggle(InputAction.CallbackContext context);
        void OnDay(InputAction.CallbackContext context);
        void OnNight(InputAction.CallbackContext context);
    }
}
